schema_version = "1.0.0"

id = "xiv_livepose_importer"
version = "1.0.0"
name = "XIV LivePose Importer"
tagline = "Imports SimpleHeels LivePose files on top of animations, allowing easy posing for animation adjustments in-game."
maintainer = "Luci"
# Supported types: "add-on", "theme"
type = "add-on"

blender_version_min = "4.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
